version: "3.9"
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.docker
    ports: 
      - '5432:5432'
    volumes:
      - vol-db:/var/lib/postgresql/data

  backend:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    env_file:
      - .env.docker
        
volumes:
  vol-db: